package com.example.controllers;
import com.example.entities.Department;
import com.example.entities.Employee;
import com.example.repositories.DepartmentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import java.util.Optional;

@CrossOrigin(origins = "*")
@Controller // This means that this class is a Controller
@RequestMapping(path="/departments") // This means URL's start with /demo (after Application path)
public class DepartmentController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DepartmentRepository departmentRepository;

    //@CrossOrigin(origins = "*")
    @GetMapping(path="/all")
    public @ResponseBody Iterable<Department> getAllDepartments() {
        // This returns a JSON or XML with the users
        return departmentRepository.findAll();
    }

    /**
     * @param department
     * @return message of status
     */
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewDepartment(@RequestBody Department department) {
        departmentRepository.save(department);
        return "Saved";
    }
}
