package com.example.controllers;
import com.example.entities.Employee;
import com.example.repositories.EmployeeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@CrossOrigin(origins = "*")
@Controller // This means that this class is a Controller
@RequestMapping(path="/employees") // This means URL's start with /demo (after Application path)
public class EmployeeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmployeeRepository employeeRepository;

    //@CrossOrigin(origins = "*")

    /**
     * @return Return a list of employees
     */
    @GetMapping(path="/all")
    public @ResponseBody Iterable<Employee> getAllEmployees() {
        // This returns a JSON or XML with the users
        return employeeRepository.findAll();
    }

    /**
     * @param employee
     * @return message of status
     */
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewEmployee(@RequestBody Employee employee) {
        //TO-DO: Validate department

        employeeRepository.save(employee);
        return "Saved";
    }
}
